## Ejemplo 1: Usando la librería Request

### 1. Objetivos:
    - Aprender a usar la librería Request para hacer peticiones HTTP

---
    
### 2. Desarrollo:

In [1]:
import requests
import pandas as pd

Vamos a hacer peticiones a una api de la NASA que ofrece datos sobre objetos que orbitan cerca de la Tierra. Pueden ver la documentación [aquí](https://api.nasa.gov/). Ahí podemos ver los endpoints y la manera en la que se usa la Api Key. Ve a la página y consigue tu propia Api Key para que puedas realizar los ejercicios.

Ahora, para empezar, necesitamos nuestro endpoint y nuestro diccionario de parámetros.

In [13]:
endpoint = 'https://api.nasa.gov/neo/rest/v1/neo/browse/'
payload = {'api_key': 'cjjlrLngF0fSCT2fsCJnSKHrBtohseZUWfd1osYt'}

Ambos se los pasamos al método `GET` de requests para realizar la petición a ese endpoint y enviar los parámetros como información extra que el API necesita para validar nuestra petición:

In [14]:
r = requests.get(endpoint, params=payload)

Ahora, podemos leer lo siguiente de nuestro objeto de respuesta:

In [15]:
r.status_code

200

r.json()

¡Esa es una respuesta muy larga! Vamos a diseccionarla:

In [17]:
json = r.json()

In [18]:
json.keys()

dict_keys(['links', 'page', 'near_earth_objects'])

In [19]:
json['links']

{'next': 'http://api.nasa.gov/neo/rest/v1/neo/browse?page=1&size=20&api_key=cjjlrLngF0fSCT2fsCJnSKHrBtohseZUWfd1osYt',
 'self': 'http://api.nasa.gov/neo/rest/v1/neo/browse?page=0&size=20&api_key=cjjlrLngF0fSCT2fsCJnSKHrBtohseZUWfd1osYt'}

In [20]:
json['page']

{'size': 20, 'total_elements': 32803, 'total_pages': 1641, 'number': 0}

In [21]:
data = json['near_earth_objects']

In [22]:
data[0]

{'links': {'self': 'http://api.nasa.gov/neo/rest/v1/neo/2000433?api_key=cjjlrLngF0fSCT2fsCJnSKHrBtohseZUWfd1osYt'},
 'id': '2000433',
 'neo_reference_id': '2000433',
 'name': '433 Eros (A898 PA)',
 'name_limited': 'Eros',
 'designation': '433',
 'nasa_jpl_url': 'http://ssd.jpl.nasa.gov/sbdb.cgi?sstr=2000433',
 'absolute_magnitude_h': 10.31,
 'estimated_diameter': {'kilometers': {'estimated_diameter_min': 23.0438466577,
   'estimated_diameter_max': 51.5276075896},
  'meters': {'estimated_diameter_min': 23043.8466576534,
   'estimated_diameter_max': 51527.6075895943},
  'miles': {'estimated_diameter_min': 14.3187780415,
   'estimated_diameter_max': 32.0177610556},
  'feet': {'estimated_diameter_min': 75603.1738682955,
   'estimated_diameter_max': 169053.8360842445}},
 'is_potentially_hazardous_asteroid': False,
 'close_approach_data': [{'close_approach_date': '1900-12-27',
   'close_approach_date_full': '1900-Dec-27 01:30',
   'epoch_date_close_approach': -2177879400000,
   'relative_velocity': {'kilometers_per_second': '5.5786191875',
    'kilometers_per_hour': '20083.0290749201',
    'miles_per_hour': '12478.8132604691'},
   'miss_distance': {'astronomical': '0.3149291693',
    'lunar': '122.5074468577',
    'kilometers': '47112732.928149391',
    'miles': '29274494.7651919558'},
   'orbiting_body': 'Earth'},
  {'close_approach_date': '1907-11-05',
   'close_approach_date_full': '1907-Nov-05 03:31',
   'epoch_date_close_approach': -1961526540000,
   'relative_velocity': {'kilometers_per_second': '4.3944908885',
    'kilometers_per_hour': '15820.1671985367',
    'miles_per_hour': '9830.0366684463'},
   'miss_distance': {'astronomical': '0.4714855425',
    'lunar': '183.4078760325',
    'kilometers': '70533232.893794475',
    'miles': '43827318.620434755'},
   'orbiting_body': 'Earth'},
  {'close_approach_date': '1917-04-20',
   'close_approach_date_full': '1917-Apr-20 21:19',
   'epoch_date_close_approach': -1663036860000,
   'relative_velocity': {'kilometers_per_second': '4.8167840184',
    'kilometers_per_hour': '17340.4224662258',
    'miles_per_hour': '10774.6641707501'},
   'miss_distance': {'astronomical': '0.499257206',
    'lunar': '194.211053134',
    'kilometers': '74687814.59975122',
    'miles': '46408855.985038036'},
   'orbiting_body': 'Earth'},
  {'close_approach_date': '1924-03-05',
   'close_approach_date_full': '1924-Mar-05 22:13',
   'epoch_date_close_approach': -1446083220000,
   'relative_velocity': {'kilometers_per_second': '4.5960548855',
    'kilometers_per_hour': '16545.797587763',
    'miles_per_hour': '10280.915173352'},
   'miss_distance': {'astronomical': '0.3597864889',
    'lunar': '139.9569441821',
    'kilometers': '53823292.394218643',
    'miles': '33444243.0636095534'},
   'orbiting_body': 'Earth'},
  {'close_approach_date': '1931-01-30',
   'close_approach_date_full': '1931-Jan-30 04:07',
   'epoch_date_close_approach': -1228247580000,
   'relative_velocity': {'kilometers_per_second': '5.9208185341',
    'kilometers_per_hour': '21314.9467227704',
    'miles_per_hour': '13244.2789789347'},
   'miss_distance': {'astronomical': '0.1740731458',
    'lunar': '67.7144537162',
    'kilometers': '26040971.835879446',
    'miles': '16181109.5707945148'},
   'orbiting_body': 'Earth'},
  {'close_approach_date': '1938-01-13',
   'close_approach_date_full': '1938-Jan-13 22:04',
   'epoch_date_close_approach': -1008726960000,
   'relative_velocity': {'kilometers_per_second': '6.0840524046',
    'kilometers_per_hour': '21902.5886564605',
    'miles_per_hour': '13609.4168237879'},
   'miss_distance': {'astronomical': '0.2150052405',
    'lunar': '83.6370385545',
    'kilometers': '32164326.017637735',
    'miles': '19985985.424901343'},
   'orbiting_body': 'Earth'},
  {'close_approach_date': '1944-11-27',
   'close_approach_date_full': '1944-Nov-27 01:41',
   'epoch_date_close_approach': -791936340000,
   'relative_velocity': {'kilometers_per_second': '3.626098636',
    'kilometers_per_hour': '13053.9550896485',
    'miles_per_hour': '8111.2200388986'},
   'miss_distance': {'astronomical': '0.4030090561',
    'lunar': '156.7705228229',
    'kilometers': '60289296.383270507',
    'miles': '37462031.6350747166'},
   'orbiting_body': 'Earth'},
  {'close_approach_date': '1961-04-04',
   'close_approach_date_full': '1961-Apr-04 09:08',
   'epoch_date_close_approach': -275928720000,
   'relative_velocity': {'kilometers_per_second': '3.7078364482',
    'kilometers_per_hour': '13348.2112136055',
    'miles_per_hour': '8294.0593510317'},
   'miss_distance': {'astronomical': '0.4424921301',
    'lunar': '172.1294386089',
    'kilometers': '66195880.154722887',
    'miles': '41132212.6021023606'},
   'orbiting_body': 'Earth'},
  {'close_approach_date': '1968-02-11',
   'close_approach_date_full': '1968-Feb-11 13:46',
   'epoch_date_close_approach': -59566440000,
   'relative_velocity': {'kilometers_per_second': '6.0668849725',
    'kilometers_per_hour': '21840.7859008821',
    'miles_per_hour': '13571.014994912'},
   'miss_distance': {'astronomical': '0.2662714057',
    'lunar': '103.5795768173',
    'kilometers': '39833635.134625859',
    'miles': '24751473.1315964942'},
   'orbiting_body': 'Earth'},
  {'close_approach_date': '1975-01-23',
   'close_approach_date_full': '1975-Jan-23 07:39',
   'epoch_date_close_approach': 159694740000,
   'relative_velocity': {'kilometers_per_second': '5.8253076833',
    'kilometers_per_hour': '20971.1076598791',
    'miles_per_hour': '13030.6307567732'},
   'miss_distance': {'astronomical': '0.1511341909',
    'lunar': '58.7912002601',
    'kilometers': '22609353.042813383',
    'miles': '14048800.5292673654'},
   'orbiting_body': 'Earth'},
  {'close_approach_date': '1981-12-29',
   'close_approach_date_full': '1981-Dec-29 08:05',
   'epoch_date_close_approach': 378461100000,
   'relative_velocity': {'kilometers_per_second': '5.6652718459',
    'kilometers_per_hour': '20394.9786453535',
    'miles_per_hour': '12672.6465921642'},
   'miss_distance': {'astronomical': '0.3084893271',
    'lunar': '120.0023482419',
    'kilometers': '46149346.251893277',
    'miles': '28675874.0429781426'},
   'orbiting_body': 'Earth'},
  {'close_approach_date': '1988-11-06',
   'close_approach_date_full': '1988-Nov-06 14:56',
   'epoch_date_close_approach': 594831360000,
   'relative_velocity': {'kilometers_per_second': '4.305902138',
    'kilometers_per_hour': '15501.2476969045',
    'miles_per_hour': '9631.8724925571'},
   'miss_distance': {'astronomical': '0.4676402077',
    'lunar': '181.9120407953',
    'kilometers': '69957978.998277599',
    'miles': '43469872.4247609062'},
   'orbiting_body': 'Earth'},
  {'close_approach_date': '2005-03-08',
   'close_approach_date_full': '2005-Mar-08 22:07',
   'epoch_date_close_approach': 1110319620000,
   'relative_velocity': {'kilometers_per_second': '4.4122923953',
    'kilometers_per_hour': '15884.2526231559',
    'miles_per_hour': '9869.8568590937'},
   'miss_distance': {'astronomical': '0.3655672222',
    'lunar': '142.2056494358',
    'kilometers': '54688077.782936714',
    'miles': '33981595.7867820932'},
   'orbiting_body': 'Earth'},
  {'close_approach_date': '2012-01-31',
   'close_approach_date_full': '2012-Jan-31 11:01',
   'epoch_date_close_approach': 1328007660000,
   'relative_velocity': {'kilometers_per_second': '5.9451959021',
    'kilometers_per_hour': '21402.705247412',
    'miles_per_hour': '13298.8087133156'},
   'miss_distance': {'astronomical': '0.1786758136',
    'lunar': '69.5048914904',
    'kilometers': '26729521.135077032',
    'miles': '16608954.2658937616'},
   'orbiting_body': 'Earth'},
  {'close_approach_date': '2019-01-15',
   'close_approach_date_full': '2019-Jan-15 06:01',
   'epoch_date_close_approach': 1547532060000,
   'relative_velocity': {'kilometers_per_second': '6.0449176185',
    'kilometers_per_hour': '21761.7034264303',
    'miles_per_hour': '13521.8762207172'},
   'miss_distance': {'astronomical': '0.2085986871',
    'lunar': '81.1448892819',
    'kilometers': '31205919.274956477',
    'miles': '19390459.0899223026'},
   'orbiting_body': 'Earth'},
  {'close_approach_date': '2025-11-30',
   'close_approach_date_full': '2025-Nov-30 02:18',
   'epoch_date_close_approach': 1764469080000,
   'relative_velocity': {'kilometers_per_second': '3.7288508677',
    'kilometers_per_hour': '13423.8631236067',
    'miles_per_hour': '8341.0665058878'},
   'miss_distance': {'astronomical': '0.3976474744',
    'lunar': '154.6848675416',
    'kilometers': '59487215.181119528',
    'miles': '36963641.4867163664'},
   'orbiting_body': 'Earth'},
  {'close_approach_date': '2042-04-06',
   'close_approach_date_full': '2042-Apr-06 19:02',
   'epoch_date_close_approach': 2280423720000,
   'relative_velocity': {'kilometers_per_second': '3.7252247205',
    'kilometers_per_hour': '13410.8089939193',
    'miles_per_hour': '8332.9551773606'},
   'miss_distance': {'astronomical': '0.4461417254',
    'lunar': '173.5491311806',
    'kilometers': '66741851.837964898',
    'miles': '41471463.6747876724'},
   'orbiting_body': 'Earth'},
  {'close_approach_date': '2049-02-12',
   'close_approach_date_full': '2049-Feb-12 05:38',
   'epoch_date_close_approach': 2496721080000,
   'relative_velocity': {'kilometers_per_second': '6.0590645856',
    'kilometers_per_hour': '21812.6325080767',
    'miles_per_hour': '13553.5215714769'},
   'miss_distance': {'astronomical': '0.2725553389',
    'lunar': '106.0240268321',
    'kilometers': '40773698.156568143',
    'miles': '25335601.2070526534'},
   'orbiting_body': 'Earth'},
  {'close_approach_date': '2056-01-24',
   'close_approach_date_full': '2056-Jan-24 11:03',
   'epoch_date_close_approach': 2715937380000,
   'relative_velocity': {'kilometers_per_second': '5.8207578574',
    'kilometers_per_hour': '20954.7282866821',
    'miles_per_hour': '13020.4532512442'},
   'miss_distance': {'astronomical': '0.1497821765',
    'lunar': '58.2652666585',
    'kilometers': '22407094.568364055',
    'miles': '13923122.940991759'},
   'orbiting_body': 'Earth'},
  {'close_approach_date': '2062-12-31',
   'close_approach_date_full': '2062-Dec-31 08:25',
   'epoch_date_close_approach': 2934779100000,
   'relative_velocity': {'kilometers_per_second': '5.7322434825',
    'kilometers_per_hour': '20636.0765370681',
    'miles_per_hour': '12822.4554460466'},
   'miss_distance': {'astronomical': '0.3029535232',
    'lunar': '117.8489205248',
    'kilometers': '45321201.779715584',
    'miles': '28161288.9295956992'},
   'orbiting_body': 'Earth'},
  {'close_approach_date': '2069-11-08',
   'close_approach_date_full': '2069-Nov-08 21:29',
   'epoch_date_close_approach': 3151171740000,
   'relative_velocity': {'kilometers_per_second': '4.2454176851',
    'kilometers_per_hour': '15283.5036662481',
    'miles_per_hour': '9496.5748197307'},
   'miss_distance': {'astronomical': '0.4647282185',
    'lunar': '180.7792769965',
    'kilometers': '69522351.616494595',
    'miles': '43199186.121611611'},
   'orbiting_body': 'Earth'},
  {'close_approach_date': '2086-03-11',
   'close_approach_date_full': '2086-Mar-11 22:55',
   'epoch_date_close_approach': 3666725700000,
   'relative_velocity': {'kilometers_per_second': '4.2258643769',
    'kilometers_per_hour': '15213.1117567663',
    'miles_per_hour': '9452.8360246418'},
   'miss_distance': {'astronomical': '0.3713100271',
    'lunar': '144.4396005419',
    'kilometers': '55547189.163802277',
    'miles': '34515422.8449623426'},
   'orbiting_body': 'Earth'},
  {'close_approach_date': '2093-01-31',
   'close_approach_date_full': '2093-Jan-31 15:47',
   'epoch_date_close_approach': 3884255220000,
   'relative_velocity': {'kilometers_per_second': '5.9749136221',
    'kilometers_per_hour': '21509.6890394877',
    'miles_per_hour': '13365.2842812306'},
   'miss_distance': {'astronomical': '0.1824638842',
    'lunar': '70.9784509538',
    'kilometers': '27296208.428246654',
    'miles': '16961077.4217016652'},
   'orbiting_body': 'Earth'},
  {'close_approach_date': '2100-01-16',
   'close_approach_date_full': '2100-Jan-16 11:39',
   'epoch_date_close_approach': 4103782740000,
   'relative_velocity': {'kilometers_per_second': '6.0149196633',
    'kilometers_per_hour': '21653.7107877231',
    'miles_per_hour': '13454.7737947383'},
   'miss_distance': {'astronomical': '0.2038791175',
    'lunar': '79.3089767075',
    'kilometers': '30499881.715479725',
    'miles': '18951747.693781205'},
   'orbiting_body': 'Earth'},
  {'close_approach_date': '2106-12-04',
   'close_approach_date_full': '2106-Dec-04 02:22',
   'epoch_date_close_approach': 4320872520000,
   'relative_velocity': {'kilometers_per_second': '3.8530305141',
    'kilometers_per_hour': '13870.9098509079',
    'miles_per_hour': '8618.8439570822'},
   'miss_distance': {'astronomical': '0.3922912542',
    'lunar': '152.6012978838',
    'kilometers': '58685936.047948554',
    'miles': '36465749.7209118852'},
   'orbiting_body': 'Earth'},
  {'close_approach_date': '2123-04-10',
   'close_approach_date_full': '2123-Apr-10 05:51',
   'epoch_date_close_approach': 4836779460000,
   'relative_velocity': {'kilometers_per_second': '3.7537243254',
    'kilometers_per_hour': '13513.4075714592',
    'miles_per_hour': '8396.7059434992'},
   'miss_distance': {'astronomical': '0.4497028378',
    'lunar': '174.9344039042',
    'kilometers': '67274586.667835486',
    'miles': '41802489.7481862668'},
   'orbiting_body': 'Earth'},
  {'close_approach_date': '2130-02-14',
   'close_approach_date_full': '2130-Feb-14 22:11',
   'epoch_date_close_approach': 5053011060000,
   'relative_velocity': {'kilometers_per_second': '6.0381849282',
    'kilometers_per_hour': '21737.4657416866',
    'miles_per_hour': '13506.8158659941'},
   'miss_distance': {'astronomical': '0.2781645724',
    'lunar': '108.2060186636',
    'kilometers': '41612827.540500788',
    'miles': '25857012.0280873544'},
   'orbiting_body': 'Earth'},
  {'close_approach_date': '2137-01-25',
   'close_approach_date_full': '2137-Jan-25 14:12',
   'epoch_date_close_approach': 5272179120000,
   'relative_velocity': {'kilometers_per_second': '5.8142759703',
    'kilometers_per_hour': '20931.393493074',
    'miles_per_hour': '13005.9539179604'},
   'miss_distance': {'astronomical': '0.1494623094',
    'lunar': '58.1408383566',
    'kilometers': '22359243.131520978',
    'miles': '13893389.4368983764'},
   'orbiting_body': 'Earth'},
  {'close_approach_date': '2144-01-03',
   'close_approach_date_full': '2144-Jan-03 10:26',
   'epoch_date_close_approach': 5491103160000,
   'relative_velocity': {'kilometers_per_second': '5.7943538473',
    'kilometers_per_hour': '20859.6738502169',
    'miles_per_hour': '12961.3901209861'},
   'miss_distance': {'astronomical': '0.296580393',
    'lunar': '115.369772877',
    'kilometers': '44367795.07656291',
    'miles': '27568869.475111758'},
   'orbiting_body': 'Earth'},
  {'close_approach_date': '2150-11-12',
   'close_approach_date_full': '2150-Nov-12 07:12',
   'epoch_date_close_approach': 5707523520000,
   'relative_velocity': {'kilometers_per_second': '4.1745035914',
    'kilometers_per_hour': '15028.2129289863',
    'miles_per_hour': '9337.9470835693'},
   'miss_distance': {'astronomical': '0.4609447583',
    'lunar': '179.3075109787',
    'kilometers': '68956354.029344821',
    'miles': '42847491.5292516898'},
   'orbiting_body': 'Earth'},
  {'close_approach_date': '2167-03-16',
   'close_approach_date_full': '2167-Mar-16 05:30',
   'epoch_date_close_approach': 6223152600000,
   'relative_velocity': {'kilometers_per_second': '4.026253601',
    'kilometers_per_hour': '14494.512963503',
    'miles_per_hour': '9006.3266800166'},
   'miss_distance': {'astronomical': '0.3774337428',
    'lunar': '146.8217259492',
    'kilometers': '56463283.989007836',
    'miles': '35084657.7735706968'},
   'orbiting_body': 'Earth'},
  {'close_approach_date': '2174-02-03',
   'close_approach_date_full': '2174-Feb-03 01:30',
   'epoch_date_close_approach': 6440520600000,
   'relative_velocity': {'kilometers_per_second': '6.0055431713',
    'kilometers_per_hour': '21619.9554168322',
    'miles_per_hour': '13433.7995199755'},
   'miss_distance': {'astronomical': '0.1884002692',
    'lunar': '73.2877047188',
    'kilometers': '28184278.979746604',
    'miles': '17512898.8741029752'},
   'orbiting_body': 'Earth'},
  {'close_approach_date': '2181-01-17',
   'close_approach_date_full': '2181-Jan-17 20:55',
   'epoch_date_close_approach': 6660046500000,
   'relative_velocity': {'kilometers_per_second': '5.9898389294',
    'kilometers_per_hour': '21563.4201458554',
    'miles_per_hour': '13398.6707011844'},
   'miss_distance': {'astronomical': '0.1980108125',
    'lunar': '77.0262060625',
    'kilometers': '29621995.786969375',
    'miles': '18406254.672652375'},
   'orbiting_body': 'Earth'},
  {'close_approach_date': '2187-12-06',
   'close_approach_date_full': '2187-Dec-06 23:28',
   'epoch_date_close_approach': 6877265280000,
   'relative_velocity': {'kilometers_per_second': '3.9833820614',
    'kilometers_per_hour': '14340.1754211404',
    'miles_per_hour': '8910.4273332081'},
   'miss_distance': {'astronomical': '0.3873137309',
    'lunar': '150.6650413201',
    'kilometers': '57941309.164393183',
    'miles': '36003060.0306766054'},
   'orbiting_body': 'Earth'}],
 'orbital_data': {'orbit_id': '659',
  'orbit_determination_date': '2021-05-24 17:55:05',
  'first_observation_date': '1893-10-29',
  'last_observation_date': '2021-05-13',
  'data_arc_in_days': 46582,
  'observations_used': 9130,
  'orbit_uncertainty': '0',
  'minimum_orbit_intersection': '.148662',
  'jupiter_tisserand_invariant': '4.582',
  'epoch_osculation': '2460000.5',
  'eccentricity': '.2227818894620597',
  'semi_major_axis': '1.458129136101339',
  'inclination': '10.82782330218545',
  'ascending_node_longitude': '304.2870401191066',
  'orbital_period': '643.1205824040848',
  'perihelion_distance': '1.133284372081002',
  'perihelion_argument': '178.9269951795186',
  'aphelion_distance': '1.782973900121676',
  'perihelion_time': '2459802.601698595905',
  'mean_anomaly': '110.7776526746434',
  'mean_motion': '.5597706088868498',
  'equinox': 'J2000',
  'orbit_class': {'orbit_class_type': 'AMO',
   'orbit_class_description': 'Near-Earth asteroid orbits similar to that of 1221 Amor',
   'orbit_class_range': '1.017 AU < q (perihelion) < 1.3 AU'}},
 'is_sentry_object': False}

`links` y `page` son metadata que vamos a utilizar luego para automatizar el proceso de peticiones. `data` es una lista de diccionarios que contiene los datos que queremos utilizar. Vamos a convertirlos en un `DataFrame`:

In [23]:
normalized = pd.json_normalize(data)

df = pd.DataFrame.from_dict(normalized)

df.head()

,id,neo_reference_id,name,name_limited,designation,nasa_jpl_url,absolute_magnitude_h,is_potentially_hazardous_asteroid,close_approach_data,is_sentry_object,...,orbital_data.perihelion_distance,orbital_data.perihelion_argument,orbital_data.aphelion_distance,orbital_data.perihelion_time,orbital_data.mean_anomaly,orbital_data.mean_motion,orbital_data.equinox,orbital_data.orbit_class.orbit_class_type,orbital_data.orbit_class.orbit_class_description,orbital_data.orbit_class.orbit_class_range
0,2000433,2000433,433 Eros (A898 PA),Eros,433,http://ssd.jpl.nasa.gov/sbdb.cgi?sstr=2000433,10.31,False,"[{'close_approach_date': '1900-12-27', 'close_...",False,...,1.133284372081002,178.9269951795186,1.782973900121676,2459802.601698595905,110.7776526746434,.5597706088868498,J2000,AMO,Near-Earth asteroid orbits similar to that of ...,1.017 AU < q (perihelion) < 1.3 AU
1,2000719,2000719,719 Albert (A911 TB),Albert,719,http://ssd.jpl.nasa.gov/sbdb.cgi?sstr=2000719,15.59,False,"[{'close_approach_date': '1909-08-21', 'close_...",False,...,1.194521858788897,156.2503681890173,4.079828796226027,2459956.023234763085,10.23596428095426,.2301418330768929,J2000,AMO,Near-Earth asteroid orbits similar to that of ...,1.017 AU < q (perihelion) < 1.3 AU
2,2000887,2000887,887 Alinda (A918 AA),Alinda,887,http://ssd.jpl.nasa.gov/sbdb.cgi?sstr=2000887,13.83,False,"[{'close_approach_date': '1910-01-04', 'close_...",False,...,1.061321201915153,350.4750171333043,3.883609285276582,2460678.792844005586,188.0405623183154,.2535179888765987,J2000,AMO,Near-Earth asteroid orbits similar to that of ...,1.017 AU < q (perihelion) < 1.3 AU
3,2001036,2001036,1036 Ganymed (A924 UB),Ganymed,1036,http://ssd.jpl.nasa.gov/sbdb.cgi?sstr=2001036,9.22,False,"[{'close_approach_date': '1910-02-25', 'close_...",False,...,1.244963114186642,132.4678967189769,4.086971560491093,2460569.530751926612,231.1579652145581,.2264236763113618,J2000,AMO,Near-Earth asteroid orbits similar to that of ...,1.017 AU < q (perihelion) < 1.3 AU
4,2001221,2001221,1221 Amor (1932 EA1),Amor,1221,http://ssd.jpl.nasa.gov/sbdb.cgi?sstr=2001221,17.38,False,"[{'close_approach_date': '1900-03-08', 'close_...",False,...,1.082508630279756,26.63044254343605,2.755083241500687,2459867.321948764327,49.38482790190183,.3708180698222572,J2000,AMO,Near-Earth asteroid orbits similar to that of ...,1.017 AU < q (perihelion) < 1.3 AU

¡Listo! Ahora tenemos un `DataFrame` con los datos de nuestra primera petición. En esta sesión vamos a aprender a automatizar este proceso. Pero antes, practiquemos un poco el uso de la librería `requests`.